### ISSUE TITLE
Issues when downloading files from your GEO repository

### ISSUE THREAD

**Issue by KinSimon96** [brlauuu/seurat_exploration#1]
Hello,

My laboratory (IRIBHM, Brussels) is working on the microglial development in the Zebrafish, and your study will be very helpful to elucidate some key points about it, that is why we decided to use your multiple time points datasets to carry out some bioinformatics analyses, for which I've been charged in. 
I have tried to download some of your .rds files in the GEO repository [https://www-ncbi-nlm-nih-gov.ezproxy.u-pec.fr/geo/query/acc.cgi?acc=GSE158142](url) but strange problems appeared:

- Firstly, when files are above 2GB, it only downloads 2GB, which induces obvious problems when decompressing them

- Secondly, for smaller .rds files (< 2GB), it is working correctly both via ftp and http, but directly fails when decompressing them (Checksum errors, data error,...)

Those problems appeared with differents computers using different systems (Windows 10, Mac OS, Unix), this is why I wanted to ask if you had already been awared about those isssues, or if it was working normally for you and/or your team.

Thank you in advance for your answer!

Kin Simon
Bioinformatician

**Comment by brlauuu** [comment]
Hi @KinSimon96. Sorry for a late response. Have you tried contacting NCBI support? The data were uploaded according to the instructions provided by NCBI so the error is technically not on our end. In case NCBI is unresponsive, please let me know and I will see what I can do to provide you the files otherwise.

**Comment by KinSimon96** [comment]
Hello,

Thank you very much for your reply!
I've contacted the NCBI support but they are not responding to my mail. I created this github issue because it was actually working for .rds files from other GEO repositories.
I see that you have been working with 10xGenomics and therefore CellRanger to obtain the final files, so it would be very nice from you if you could provide the barcode.tsv/features.tsv/matrix.mtx for each time point dataset, so i could start a more stringent analysis (we will be working only with microglial cells from your datasets) from the very beginning.

Thank you again,
Kin Simon

**Comment by brlauuu** [comment]
Sorry for late replies @KinSimon96. This are taking more time these days. I will see with the corresponding authors of the paper and get back to you as soon as possible. Sorry for the inconvenience.

**Comment by brlauuu** [comment]
Hi @KinSimon96, I saw that Bushra replied to you directly via email so I will close this issue. Moreover, I also tried now to download a 5gb large file, unzip it and run it in R. It all went ok. I hope it was just a glitch that would be solved quickly.
