### ISSUE TITLE
Missing clusters in ZFBrainAtlasMaster.tsv?

### ISSUE THREAD

**Issue by francoiskroll** [brlauuu/seurat_exploration#3]
Hi,

How should I interpret clusters missing from _ZFBrainAtlasMaster.tsv_?

For example, 12 hpf stage is missing clusters 3 & 6.

Thank you!

**Comment by brlauuu** [comment]
Hi,

Sorry for replying only now. Somehow this notification slipped through the cracks. I'm not 100% sure, but I think there was some cluster merging and hence some clusters were joined into other clusters. Best is to consult the SI of the paper.
